
package start.page;

import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Data_Structure extends javax.swing.JFrame {
        

    int cnt=0;
    String linkText,nameText,TeamText,PlayerText,ActionText;
    boolean Sort_flag;
    
    Linklist videos = new Linklist();
    
    public Data_Structure() {
        //this.setLocation(300, 100);
        //this.setResizable(false);
        //this.setVisible(false);
        Sort_flag = true;
        initComponents();
        //this.add(new Home());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        Team_name = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        Player_name = new javax.swing.JTextField();
        Action = new javax.swing.JTextField();
        txtLink = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MyTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        V_counter = new javax.swing.JLabel();
        Search = new javax.swing.JLabel();
        Refresh = new javax.swing.JLabel();
        Delete = new javax.swing.JLabel();
        Insert = new javax.swing.JLabel();
        Play = new javax.swing.JLabel();
        Sort = new javax.swing.JLabel();
        next = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        test = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("World Cup Highlights Tube");

        jLabel1.setText("Name");

        jLabel2.setText("Team");

        jLabel3.setText("Player");

        jLabel4.setText("Action");

        jLabel5.setText("Link");

        MyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Team", "Player", "Action", "Link"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MyTable.getTableHeader().setReorderingAllowed(false);
        MyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MyTable);

        jLabel6.setText("Videos:");

        V_counter.setText("0");

        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start/page/search-button.png"))); // NOI18N
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
        });

        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start/page/refresh-button.png"))); // NOI18N
        Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshMouseClicked(evt);
            }
        });

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start/page/delete-button.png"))); // NOI18N
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });

        Insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start/page/add-button.png"))); // NOI18N
        Insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertMouseClicked(evt);
            }
        });

        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start/page/play-button.png"))); // NOI18N
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayMouseClicked(evt);
            }
        });

        Sort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start/page/sort.png"))); // NOI18N
        Sort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SortMouseClicked(evt);
            }
        });

        next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        next.setText("next");
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });

        test.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start/page/world cup.png"))); // NOI18N
        test.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testMouseClicked(evt);
            }
        });

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start/page/update.png"))); // NOI18N
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtSearch)
                                .addGap(18, 18, 18)
                                .addComponent(Search)
                                .addGap(43, 43, 43))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Action, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player_name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(Team_name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                                        .addComponent(jButton1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(test)))
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Sort)
                                .addGap(156, 156, 156)
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Play)
                                .addGap(18, 18, 18)
                                .addComponent(Insert)
                                .addGap(18, 18, 18)
                                .addComponent(Delete)
                                .addGap(18, 18, 18)
                                .addComponent(Refresh))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(V_counter, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175)
                                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Action, Player_name, Team_name, txtLink, txtName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Delete, Insert, Play, Refresh, Sort});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sort, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Refresh)
                                .addComponent(Play, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Insert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Delete, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(update, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(V_counter)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Team_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Player_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(test)
                        .addGap(19, 19, 19))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Action, Player_name, Team_name, txtLink, txtName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Delete, Insert, Play, Refresh});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyTableMouseClicked
        DefaultTableModel tb1Model = (DefaultTableModel) MyTable.getModel();
        String tb1Name = tb1Model.getValueAt(MyTable.getSelectedRow(), 0).toString();
        String tb1Team= tb1Model.getValueAt(MyTable.getSelectedRow(), 1).toString();
        String tb1Player= tb1Model.getValueAt(MyTable.getSelectedRow(), 2).toString();
        String tb1Action= tb1Model.getValueAt(MyTable.getSelectedRow(), 3).toString();
        String tb1Link= tb1Model.getValueAt(MyTable.getSelectedRow(), 4).toString();
            txtName.setText(tb1Name);
            Team_name.setText(tb1Team);
            Player_name.setText(tb1Player);
            Action.setText(tb1Action);
            txtLink.setText(tb1Link);
            
    }//GEN-LAST:event_MyTableMouseClicked

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        nameText = txtSearch.getText();
        if (nameText.equals("")) JOptionPane.showMessageDialog(this, "Enter Video Name‼");
        else{
               String[] test=new String[5];
               test = videos.search(nameText);
                if (test==null) {
                    JOptionPane.showMessageDialog(this, "not found");
                }
            else{
                     String[] video_data= new String[5];
                    video_data=videos.search(nameText);
                   txtName.setText(video_data[0]);
                   Team_name.setText(video_data[1]);
                   Player_name.setText(video_data[2]);
                   Action.setText(video_data[3]);
                   txtLink.setText(video_data[4]);
                DefaultTableModel tb1Model = (DefaultTableModel) MyTable.getModel();
//                String data[]= videos.search(nameText);
                tb1Model.setRowCount(0);
                tb1Model.addRow(video_data);
                linkText= video_data[4];
            }
             } 
    }//GEN-LAST:event_SearchMouseClicked

    private void RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseClicked
        refresh();
           txtName.setText("");
            txtLink.setText("");
            Team_name.setText("");
            Player_name.setText("");
            Action.setText("");
    }//GEN-LAST:event_RefreshMouseClicked

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
       DefaultTableModel tb1Model = (DefaultTableModel) MyTable.getModel();
         if(MyTable.getSelectedRowCount()==0){
             JOptionPane.showMessageDialog(this, "No Videos");
         }
         else if(MyTable.getSelectedRowCount()==1){
          String test = tb1Model.getValueAt(MyTable.getSelectedRow(), 0).toString(); 
          tb1Model.removeRow(MyTable.getSelectedRow());
          videos.delete(test); 
          JOptionPane.showMessageDialog(this, "Deleted successfully ✔");
            txtName.setText("");
            txtLink.setText("");
            Team_name.setText("");
            Player_name.setText("");
            Action.setText("");
            cnt --;
            V_counter.setText(String.valueOf(cnt));
        }else if(MyTable.getSelectedRowCount()>1){
            JOptionPane.showMessageDialog(this, "Please Select Single Row For Delete.. !");
        }
        videos.print();
    }//GEN-LAST:event_DeleteMouseClicked

    private void InsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertMouseClicked
        nameText = txtName.getText();
        linkText = txtLink.getText();
       
       // ImageIcon icon = new ImageIcon();
        if (nameText.equals("") || linkText.equals("") || Team_name.equals("") || Player_name.equals("") || Action.equals("")  ) {
            JOptionPane.showMessageDialog(this, "invalid insertion");
        }
        else{
            videos.insert(txtName.getText(), Team_name.getText(), Player_name.getText(), Action.getText(), txtLink.getText());
            String data[]= {txtName.getText(),Team_name.getText(),Player_name.getText(), Action.getText(), txtLink.getText() };
            DefaultTableModel tb1Model = (DefaultTableModel) MyTable.getModel();
            tb1Model.addRow(data);
            videos.print();
            txtName.setText("");
            txtLink.setText("");
            Team_name.setText("");
            Player_name.setText("");
            Action.setText("");
            JOptionPane.showMessageDialog(this, "Inserted successfully ✔");
            cnt ++;
            V_counter.setText(String.valueOf(cnt));
            
        }
    }//GEN-LAST:event_InsertMouseClicked

    private void SortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SortMouseClicked
        if (Sort_flag) {
        videos.sortLinkedListasc();
        videos.print();
        Sort_flag = false;
        Sort.setIcon(new javax.swing.ImageIcon("C:\\Users\\mohse\\Downloads\\Icon\\sortD.png"));
        refresh();
        
        }
        
     else{
        videos.sortLinkedListdsc();
        videos.print();
        
        Sort_flag = true;
        Sort.setIcon(new javax.swing.ImageIcon("C:\\Users\\mohse\\Downloads\\Icon\\sort.png"));
        refresh();
    }
        
        //
        
        
    }//GEN-LAST:event_SortMouseClicked

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
            if(videos.size == 0){
            JOptionPane.showMessageDialog(this, "No Videos!");
        }   
        
        else if(videos.ptr == null){
                 JOptionPane.showMessageDialog(this, "Last Video!");
            }  
            else{
                 txtName.setText(videos.ptr.name);
                 Team_name.setText(videos.ptr.Team);
                 Player_name.setText(videos.ptr.Player);
                 Action.setText(videos.ptr.Action);
                 txtLink.setText(videos.ptr.link);
                 videos.ptr = videos.ptr.next;
                 videos.ptr = videos.head;
            }

    }//GEN-LAST:event_nextMouseClicked

    private void testMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testMouseClicked

    }//GEN-LAST:event_testMouseClicked

    private void PlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseClicked
//Y:\\Youssef\\Photo\\friends.mp4
        nameText = txtName.getText();  
        linkText = txtLink.getText();
//        VideoPlayer videoPlayer = new VideoPlayer("Y:\\Youssef\\Photo\\friends.mp4");

        try {
            Desktop.getDesktop().open(new File(linkText)); 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No Video");
        }
    }//GEN-LAST:event_PlayMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
            nameText = txtName.getText();
        if (nameText.equals("")) JOptionPane.showMessageDialog(this, "Empty Name");

        else{
            String[] video_data=videos.search(nameText);
            videos.update(nameText, txtLink.getText());
            JOptionPane.showMessageDialog(this, "Updated successfully ✔");
            txtName.setText("");
            txtLink.setText("");
            Team_name.setText("");
            Player_name.setText("");
            Action.setText("");
             refresh();
        }
        videos.print();
    }//GEN-LAST:event_updateMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
            nameText = txtName.getText();
        if (nameText.equals("")) JOptionPane.showMessageDialog(this, "Empty Name");

        else{
            String[] video_data=videos.search(nameText);
            videos.update(nameText, txtLink.getText());
            JOptionPane.showMessageDialog(this, "Updated successfully ✔");
            txtName.setText("");
            txtLink.setText("");
            Team_name.setText("");
            Player_name.setText("");
            Action.setText("");
             refresh();
        }
        videos.print();
        
    }//GEN-LAST:event_jButton1ActionPerformed
public void refresh(){
     Node current = videos.head;
     DefaultTableModel tb1Model = (DefaultTableModel) MyTable.getModel();
     tb1Model.setRowCount(0);
     String[] refresh_data = new String[5] ; 
     while (current != null) {
         refresh_data[0]= current.name ; 
         refresh_data[1]= current.Team ;
         refresh_data[2]= current.Player ;
         refresh_data[3]= current.Action ;
         refresh_data[4]= current.link ;
         tb1Model.addRow(refresh_data);
         current = current.next;
     } 
}

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Structure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Structure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Structure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Structure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Structure().setVisible(true);

                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Action;
    private javax.swing.JLabel Delete;
    private javax.swing.JLabel Insert;
    private javax.swing.JTable MyTable;
    private javax.swing.JLabel Play;
    private javax.swing.JTextField Player_name;
    private javax.swing.JLabel Refresh;
    private javax.swing.JLabel Search;
    private javax.swing.JLabel Sort;
    private javax.swing.JTextField Team_name;
    private javax.swing.JLabel V_counter;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel next;
    private javax.swing.JLabel test;
    private javax.swing.JTextField txtLink;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
